name = "syed-portfolio-chat"
main = "worker.js"
compatibility_date = "2024-09-20"

# Optional: allow only your GitHub Pages domain
[vars]
ALLOWED_ORIGIN = "https://YOUR_GH_USERNAME.github.io"

# Deploy to workers.dev by default. After deploy you'll get:
# https://syed-portfolio-chat.YOUR_ACCOUNT.workers.dev/chat

# Set the secret (will not be stored in this file):
# wrangler secret put GROQ_API_KEY